### ISSUE TITLE
Feedback  & Confusion while installling forem selfhost

### ISSUE THREAD

**Issue by devops-school** [forem/selfhost#13]
I was trying to install  forem selfhost in AWS Fedora CoreOs. and following instructions.

Document - https://github.com/forem/selfhost/

Background - I am using following region in AWS with following AMI ID
- Region: ap-south-1
Release: 34.20210626.3.1
Image: ami-0de887f898b8b9edf

Confusion#1 - Big Confusion in "WORKSTATION" and VMs for AWS? Instructions is so confusing where we should run which one?

Confusion#2  - Step 1-7 - I run in AWS VMs of Fedora CoreOS where i am installing forem but Suddenly Step 8 - "on your workstation" change entire senario of my understanding?

Confusion#2  - Soneone need to explin that What you are trying to do?
1. Are you creating AWS Ec2 instance using ansble script and installing Forem in the NEW AWS EC2 instance created by script??
or
2. Are you trying to RUN Step 1-11 in the Ec2 instance where Forem should be installed?

**Comment by jdoss** [comment]
You run the Ansible playbook from your workstation and it does everything for you. You don't run the playbook on Fedora CoreOS. You shouldn't have to pick an AMI either. The playbook does it for you.

**Comment by cmgorton** [comment]
Hey @devops-school I have a tutorial on setting up Forem selfhost on AWS that should be posted on [forem.dev](https://forem.dev/) tomorrow. It is a more detailed walkthrough than what we have in the quick start guide. I will link it here once it is posted and you can let me know if that helps clear some things up for you. 
Also like @jdoss mentioned a lot of the setup is done for you through the Ansible playbook. The instructions in the [AWS section](https://github.com/forem/selfhost#aws) (If that is the cloud provider you are using) are all you need. The walkthrough I will link you to when it is live does give step by step instructions on navigating the AWS console though and may clear up some of the confusion for you.

**Comment by cmgorton** [comment]
Hey @devops-school here is a series of guides with more details on setting up your selfhost Forem including on one setting up AWS. 
[Official Selfhost Guides](https://forem.dev/coffeecraftcode/series/8)

If you have any more trouble setting up your Forem please feel free to create a post on [forem.dev](https://forem.dev/) and tag it with the [#help](https://forem.dev/t/help) and [#selfhost](https://forem.dev/t/selfhost) tags. Someone on the team or in the community will be able to help you there.
