### ISSUE TITLE
Failed to parse /var/home/core/selfhost/inventory/forem/setup.yml

### ISSUE THREAD

**Issue by devops-school** [forem/selfhost#14]
`$ ansible-playbook -i inventory/forem/setup.yml playbooks/providers/aws.yml
[WARNING]:  * Failed to parse /var/home/core/selfhost/inventory/forem/setup.yml with ini plugin: Invalid host pattern '---' supplied, '---' is normally a sign this is
a YAML file.
[WARNING]:  * Failed to parse /var/home/core/selfhost/inventory/forem/setup.yml with yaml plugin: We were unable to read either as JSON nor YAML, these are the errors
we got from each: JSON: Expecting value: line 1 column 1 (char 0)  Syntax Error while loading YAML.   could not find expected ':'  The error appears to be in
'/var/home/core/selfhost/inventory/forem/setup.yml': line 85, column 11, but may be elsewhere in the file depending on the exact syntax problem.  The offending line
appears to be:            $ANSIBLE_VAULT;1.1;AES256           62376137383864393461613561353234643230666431643935303533346631393537363564366334           ^ here
[WARNING]: Unable to parse /var/home/core/selfhost/inventory/forem/setup.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Deploy Forem to AWS] *********************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP *************************************************************************************************************************************************************

[core@ip-172-31-9-59 selfhost]$
`

**Comment by cotocusin** [comment]
This is Solved.

Solution was Space issues in Token

![image](https://user-images.githubusercontent.com/70873768/126052016-da3cdc61-51e6-43bf-9cda-fba6e47361db.png)

**Comment by roytmanpiccoli** [comment]
@cotocusin Greate I have this issue, simple space :D lol, Thanks
