### ISSUE TITLE
forem Install Error: Transpile Butane YAML into JSON

### ISSUE THREAD

**Issue by cotocusin** [forem/selfhost#15]
TASK [butane : Transpile Butane YAML into JSON] ************************************************************************************************************************
fatal: [forem]: FAILED! => changed=true
  cmd: |-
    butane  --strict "/tmp/butane_input_ajt1wc2f.bu"
  delta: '0:00:00.061281'
  end: '2021-07-18 00:11:02.752356'
  msg: non-zero return code
  rc: 1
  start: '2021-07-18 00:11:02.691075'
  stderr: 'Error translating config: Error unmarshaling yaml: yaml: line 501: found character that cannot start any token'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

PLAY RECAP *************************************************************************************************************************************************************
forem                      : ok=14   changed=4    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by devops-school** [comment]
vi /tmp/butane_input_y1eomduj.bu

![image](https://user-images.githubusercontent.com/44023974/126052523-8195daf7-d93a-4781-9197-18ffde7e1815.png)

**Comment by jdoss** [comment]
That shouldn't line break there. Did you make changes to the template?

**Comment by cmgorton** [comment]
> TASK [butane : Transpile Butane YAML into JSON] ************************************************************************************************************************
> fatal: [forem]: FAILED! => changed=true
> cmd: |-
> butane --strict "/tmp/butane_input_ajt1wc2f.bu"
> delta: '0:00:00.061281'
> end: '2021-07-18 00:11:02.752356'
> msg: non-zero return code
> rc: 1
> start: '2021-07-18 00:11:02.691075'
> stderr: 'Error translating config: Error unmarshaling yaml: yaml: line 501: found character that cannot start any token'
> stderr_lines:
> stdout: ''
> stdout_lines:
> 
> PLAY RECAP *************************************************************************************************************************************************************
> forem : ok=14 changed=4 unreachable=0 failed=1 skipped=1 rescued=0 ignored=0

Hey @cotocusin could you give a little more detail about what step you were on when you got this error? Where you running the playbook and if so for what cloud provider? Thanks!

**Comment by jdoss** [comment]
I am closing this since there hasn't been a response in over two weeks. If you are still having issues with setting up your Forem, please consider posting on https://forem.dev for help.
