### ISSUE TITLE
"Launch Forem instance for {{ app_domain }}" fails

### ISSUE THREAD

**Issue by leewynne** [forem/selfhost#18]
Hi there, nearly there with this now. Just this error with ec2 instance creation. I have the values that make up app_domain set in my setup.yml file

fatal: [forem]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: No first item, sequence was empty.

    The error appears to be in '/Users/lee/Documents/Productions/Git.nosync/forem/selfhost/selfhost/playbooks/providers/aws.yml': line 170, column 5, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

      - name: "Launch Forem instance for {{ app_domain }}"
        ^ here
    We could be wrong, but this one looks like it might be an issue with
    missing quotes. Always quote template expression brackets when they
    start a value. For instance:

        with_items:
          - {{ foo }}

    Should be written as:

        with_items:
          - "{{ foo }}"

**Comment by jdoss** [comment]
What are your values for app_domain in your setup.yml?

**Comment by leewynne** [comment]
Hey 👋🏼 

forem_domain_name: sustainablefinds.org
          # CHANGE_REQUIRED — default_email: your_email@example.com
          default_email: yo@sustainablefinds.org
          forem_subdomain_name: www # can be subdomain, i.e. "community" in community.mainwebsite.com
          forem_server_hostname: host # You may change to something else if you choose (i.e. server, srv, etc)
          app_domain: "{{ forem_subdomain_name }}.{{ forem_domain_name }}"

**Comment by leewynne** [comment]
I know what the issue is. It isn't related to the repo, it was AWS related. There was a small issue in the custom VPC that I was deploying to.

Now deployed successfully to default and custom VPCs!

Might be an idea to set some default AWS requirements when deploying to a custom VPC? Not sure 🤔 

Will close the issue 😎😎
