### ISSUE TITLE
For AWS deployment, is it a good idea to auto assign an elastic IP during the build?

### ISSUE THREAD

**Issue by leewynne** [forem/selfhost#20]
Hi there,

Test deployed into AWS numerous times in various conditions, works great! Just thought of this though:

I noticed that when deployed, the ec2 instance receives a standard nonpersistent public IP that refreshes on reboot and during other conditions.

Have you considered auto-assigning an elastic IP? They are free when attached to an ec2 instance and persist through reboots and changes and can be moved to other instances

**Comment by jdoss** [comment]
I think that really depend on _your_ usecase. Adding in EIP makes sense if you want to spin up a new instance and migrate over to it without having to DNS gymnastics. We use NLBs for Forem Cloud for this very case. 

That said, there are a very large amount of design choices you can make with deploying Forem and we really wanted the base cloud automation in this repo to be as cheap, simple, and reproducible as possible. Also, we don't want to dictate how you deploy your cloud resources and the provider playbooks are more of an example of how you can deploy Fedora CoreOS. You can make some chances to the butane templates and launch Forem in a HA setup. We do that with Forem Cloud.

**Comment by leewynne** [comment]
Thanks for the response Joe! I'll close the issue 🙌

**Comment by shellixsmart** [comment]
Guys how can you connect to your server? I can not find automatically generated key pair
