### ISSUE TITLE
Missing AWS key pair pem file

### ISSUE THREAD

**Issue by shellixsmart** [forem/selfhost#22]
It automatically generates AWS key pair / pem file. However required pem file is missing. Which is needed in order to reach the server through SSH.

**Comment by omenking** [comment]
When you use selfhost, it setups the EC2 server for you. It's not using EC2 Keypairs. EC2 keypairs happen when you set up an EC2 instance manually and this appears just before its launch in the AWS console.

You generate a SSH key locally and use that. The reason I can tell you are not generating a local key is you mentioned `pem` but when you use `ssh-keygen -t rsa` that doesn't generate out a `.pem` file.

**Comment by shellixsmart** [comment]
Thank you @omenking @cmgorton
