### ISSUE TITLE
Redirect non www to www

### ISSUE THREAD

**Issue by edimanlmp** [forem/selfhost#24]
I installed forem using www as subdomain and is working correctly. However is there a way to redirect non www to www? Example:

https://domain.com   -> https://www.domain.com

If i go currently to https://domain.com it retrieves server not found error.

**Comment by akhil-naidu** [comment]
See this is not an issue with Forem. Depending upon your DNS provider check the documentation to create a `301 Redirect`. 301 Redirect for `@ -> www`
