### ISSUE TITLE
Google Cloud missing in requirements.yml

### ISSUE THREAD

**Issue by cmgorton** [forem/selfhost#29]
**Describe the bug**
During the MLH workshop we noticed that Google Cloud is missing from the requirements.yml file so using `ansible-galaxy collection install -r requirements.yml` as mentioned in the docs would not work to install the Google Cloud collection.

**To Reproduce**
1. Go to requirements.yml
2. See that there is no Google Cloud mentioned in the file.

**Comment by jdoss** [comment]
Fixed! 🕺🏼
