### ISSUE TITLE
Sir can i use amazon lightsail or vultr to self host forem please reply

### ISSUE THREAD

**Issue by maxmod** [forem/selfhost#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS (please complete the following information):**
 - Linux
 - MacOS

**Cloud Provider (please complete the following information):**
 - AWS
 - DigitalOcean
 - Google Cloud Provider
 - Other

Sir can i use amazon lightsail or vultr to self host forem please reply
**Additional context**

**Comment by andygeorge** [comment]
Hey @maxmod, thank you for your interest in Selfhost! Currently Selfhost supports running a Forem on AWS (using an EC2 instance), DigitalOcean, and GCP.

If you have specific questions on setting up your own Selfhost instance, we recommend joining https://forem.dev/, our community for Forem Creators and Builders.
