### ISSUE TITLE
I get 404 page not found after following the guide

### ISSUE THREAD

**Issue by gkkirilov** [forem/selfhost#43]
**Describe the bug**
I get 404 page not found instead of creating an admin account page

**To Reproduce**
Follow @jdoss https://www.youtube.com/watch?v=af7N_-M1-3Y and deploy on GCP
As the final step restart traefik service on  server
Open domain see no ssl certificate installed and 404 page not found error.

**Expected behavior**
Register first user page

**Screenshots**
![image](https://user-images.githubusercontent.com/8720012/132166319-a4c1a2cb-2f4c-49d6-a4f4-3d1599e94a29.png)

**OS (please complete the following information):**
 - Ubuntu

**Cloud Provider (please complete the following information):**
 - Google Cloud Provider

**Additional context**
This guy has the same problem -> [here](https://forem.dev/tien/404-page-not-found-after-all-services-run-4h3a)

**Comment by jdoss** [comment]
Hey @gkkirilov we found a bug that just got fixed this morning. https://github.com/forem/selfhost/pull/45 Just pull down the latest main branch from GitHub and you can either delete your setup in GCP and relaunch or SSH into your server as the `core` user, `sudo vi /opt/forem/configs/traefik/dynamic.toml`, change `ReferrerPolicy = same-origin` to `ReferrerPolicy = "same-origin"`, save the file `:wq` and then restart Traefik `sudo systemctl restart forem-traefik` and that should fix this issue for you.

**Comment by gkkirilov** [comment]
@jdoss worked like a charm, thank you
