### ISSUE TITLE
Export to another vps

### ISSUE THREAD

**Issue by abdiasriver** [forem/selfhost#57]
How i export all forem site, to another vps?

**Comment by jdoss** [comment]
Here are the steps I would use to move your Forem from one VPS to another. 

1. Follow this https://github.com/forem/selfhost#backup-your-forem-data to backup your Forem data
2. Download that backup tar.gz to your workstation via SCP
3. Run the selfhost playbook to setup another VPS
4. Log in to the new VPS and stop Forem `foremctl stop`
5. Copy the backup tar.gz file to the new VPS using SCP
6. Move the backup tar.gz file to `/opt` on the new VPS
7. On the VPS as the root user remove `rm -rf /opt/forem`
8. On the new VPS as the root user extract `tar xzf 2021-11-24-forem-data.tar.gz`
9. On the new VPS as the root user move the forem data into the right place `mv opt/forem /opt/forem`
10. Start your forem with `foremctl start`

I have not tested these steps, but this should get you most of the way to moving your Forem from VPS to another.

**Comment by jdoss** [comment]
I am going to close this issue for now. Please let us know if you have any other questions.
