### ISSUE TITLE
S3 permissions not updated on repeated runs leads to server initialization error

### ISSUE THREAD

**Issue by alberthuang24** [forem/selfhost#60]
**Describe the bug**
S3 permissions not updated on repeated runs leads to server initialization error.

When I ran ansible for the first time, for some reason I didn't set it up properly and ran it a second time, the S3 permissions were not updated. This resulted in the following image. forem.ign failed to download and resulted in a system initialization error

**To Reproduce**
1. Run `ansible-playbook -i inventory/forem/setup.yml playbooks/providers/aws.yml`
2. Delete the old EC2 Instance
2. Rerun `ansible-playbook -i inventory/forem/setup.yml playbooks/providers/aws.yml`
3. Goto AWS dashboard show system logs
4. See an error

**Screenshots**
![3hV5IHqnVM](https://user-images.githubusercontent.com/20190812/149656261-92f98945-683e-43d0-9b32-948213220a00.png)

**OS (please complete the following information):**
 - MacOS

**Cloud Provider (please complete the following information):**
 - AWS

**Additional context**

**Comment by jdoss** [comment]
The playbooks are not fully idempotent. It's hard to say why that S3 bucket didn't get set with the correct permissions. Did Ansible die off with an error? That would be handy to help you debug this.

I'd delete the bucket and try again. If it still fails, please give us the current permissions on the bucket and policy. It should have this policy set:

https://github.com/forem/selfhost/blob/main/playbooks/providers/aws.yml#L105-L122

**Comment by alberthuang24** [comment]
> The playbooks are not fully idempotent. It's hard to say why that S3 bucket didn't get set with the correct permissions. Did Ansible die off with an error? That would be handy to help you debug this.
> 
> 
> 
> I'd delete the bucket and try again. If it still fails, please give us the current permissions on the bucket and policy. It should have this policy set:
> 
> 
> 
> https://github.com/forem/selfhost/blob/main/playbooks/providers/aws.yml#L105-L122

Yes, it worked after I deleted the old bucket
